### ISSUE TITLE
Can you make a custom component for esphome with this?

### ISSUE THREAD

**Issue by NonaSuomy** [RobTillaart/rotaryDecoderSwitch#4]
https://esphome.io/components/pcf8574.html

https://esphome.io/components/external_components.html

https://esphome.io/custom/custom_component.html

Someone did something similar with a 16x2 char display https://esphome.io/components/display/lcd_display.html

**Comment by RobTillaart** [comment]
Good morning, 
Looks interesting, I am not familiar with the details of ESPhome. Know it by name but not worked with it. So it would take time to dive into. But of course it could be made.

For me it is a low prio enhancement as it is beyond core code and not a bug. As I am in the middle of big maintenance for all my libraries it might be February next year before I will investigate. Does that fit in your time schedule?

**Comment by NonaSuomy** [comment]
That would be wonderful. Thank you.

I was looking at other libraries where people did something like it. It seems pretty straightforward seems you pull in the Arduino libraries with that external component from your github then esphome has some boilerplate that basically just looks like an Arduino wrapper "setup / loop" so maybe you just dump one of your examples in there and then magic happens.

**Comment by RobTillaart** [comment]
If in the meantime you have additional documentation, please post the links here

**Comment by NonaSuomy** [comment]
Sure thing! Will keep editing and adding to this post. Change the paths and package manager as needed:

### Basic Install Docker / ESPHome / Home Assistant

### Docker Install
```
sudo pacman -Sy docker docker-compose bridge-utils
```

### Mounting a drive for docker images
```
mkdir -p /var/lib/libvirt/images/usb001/docker
mount /dev/sdb1 /var/lib/libvirt/images/usb001
```

### Change the docker default directory
/etc/docker/daemon.json
```
{
  "data-root": "/var/lib/libvirt/images/usb001/docker"
}
```

### Install DHCP Plugin for docker
```
docker plugin install ghcr.io/devplayer0/docker-net-dhcp:release-linux-arm64
```

Create a network bridge
```
brctl addbr brv100
```
Add interfaces to your primary adapter eth0 or wlan0 etc.
```
brctl addif brv100 eth0
```
Show the bridge
```
brctl show
```
Set the bridge device up
```
ip link set dev brv100 up
```
Create the docker bridge dbrv100 and attach it to our network bridge brv100
```
sudo docker network create -d ghcr.io/devplayer0/docker-net-dhcp:release-linux-amd64 --ipam-driver null -o bridge=brv100 dbrv100
```

### ESPHome
Make a folder for ESPHome

```
sudo mkdir -p /var/lib/libvirt/images/usb001/docker-storage/esphome
cd /var/lib/libvirt/images/usb001/docker-storage/esphome
vi docker-compose.yml
```
docker-compose.yml
```
version: "3.9"
services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    restart: "no"
    volumes:
      - /var/lib/libvirt/images/usb001/docker-storage/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
    mac_address: de:ad:be:ef:00:06
    networks:
      - dhcp
    privileged: true

networks:
  dhcp:
    name: dbrv100
    external: true
```

### Bring the ESPHome container up.
```
sudo docker compose up -d
```

### HomeAssistant
Make folder for HomeAssistant
```
sudo mkdir -p /var/lib/libvirt/images/usb001/docker-storage/homeassistant
cd /var/lib/libvirt/images/usb001/docker-storage/homeassistant
vi docker-compose.yml
```
docker-compose.yml
```
#HomeAssistant Container for Docker
version: "3.9"
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /var/lib/libvirt/images/usb001/docker-storage/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    mac_address: de:ad:be:ef:00:08
    networks:
      - dhcp
    #devices:
    #  - /dev/ttyACM0:/dev/ttyACM0
    restart: "no"
    privileged: true

networks:
  dhcp:
    name: dbrv100
    external: true
```
Bring the HomeAssistant container up.
```
sudo docker compose up -d
```
Find your docker IP addresses
```
docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
/esphome - 10.13.37.10
/homeassistant - 10.13.37.11
```
Open web browser and go to the IP addresses to setup the two webUI.

Home Assitant dashboard: http://10.13.37.11:8123

Setup your user and get to the sample dashboard.

ESPHome dashboard: http://10.13.37.10:6052

Click + New Device bottom right

```
New device
A device needs to be connected to a computer using a USB cable to be added to ESPHome. Once added, ESPHome will interact with the device wirelessly.
You are not browsing the dashboard over a secure connection (HTTPS). This prevents ESPHome from being able to install this on devices connected to this computer.
You will still be able to install ESPHome by connecting the device to the computer that runs the ESPHome dashboard.
Alternatively, you can use ESPHome Web to prepare a device for being used with ESPHome using this computer.
OPEN ESPHOME WEB or CONTINUE
```
Click OPEN ESPHOME WEB which will take you here: https://web.esphome.io/?dashboard_wizard

Connect the ESP to your computer USB port and Follow the on-screen prompts to setup the ESP
```
ESP Device
Connect the ESP8266 or ESP32 to your computer and click on connect to be able to manage your device.
CONNECT
```
Click CONNECT

Select the COM Port or DEV device from your platform that shows up and click connect and install.

When you see the Installation Complete window, click the Next button and enter your WiFI credentials, and hit Connect button.

If this doesn't happen the device may show up as an AP that you can connect to with a phone to then setup and put on your wifi.

Now, you can visit your new ESPHome device, and add it to Home Assistant.

Edit its config from the ESPHome dashboard
Copy the generated keys in your file to the secrets.yaml file accessed by the button on the top right of the ESPHome dashboard 

```
use_address_wifi004: "10.13.37.114"
use_address_eth004: "10.13.37.117"
encryption_key004: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX="
ota_pass004: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
fallbackhotspot004: "XXXXXXXXXXXX"
```

Device YAML
```
#TTGO T-Internet PoE 1.0 I2C to Arduino I2C Expander

#PIN Header:
# IO34 IO35
# IO16 IO32
# IO33 IO12
# IO04 IO15
# IO32 IO14

# Internet Module HR861153C
# RXD0 IO25
# RXD1 IO26
# CRCDV IO27
# MDC IO23
# TXD1 IO22
# TX_EN IO21
# TXD0 IO19
# MIDIO IO18

# TF Card
# MOSI IO12
# SCLK IO15
# CS IO13
# MISO IO02

# Arduino
# Arduino Rotary Encoder A
# Arduino D02
# Arduino Rotary Encoder B
# Arduino D03
# Arduino Extender DHT22
# Arduino D04
# Arduino Halleffect Sensor Closed
# Arduino D05
# Arduino Halleffect Sensor Open
# Arduino D06
# Arduino Relay 1
# Arduino D07
# Arduino Relay 2
# Arduino D08

esphome:
  name: ttgo-poe-001
  includes:
    - arduino_port_expander.h

esp32:
  board: esp32-poe
  #board: esp32dev
  framework:
    type: arduino

# Define I2C device
# for an ESP8266/32 SDA is D2 and goes to Arduino's A4
#                   SCL is D1 and goes to Arduino's A5
i2c:
  id: i2c_component
  sda: 14
  scl: 16
  scan: true
  
# Enable logging
logger:
  level: DEBUG

#ethernet:
#  type: LAN8720
#  mdc_pin: GPIO23
#  mdio_pin: GPIO18
#  clk_mode: GPIO17_OUT
#  phy_addr: 0
#  use_address: !secret use_address_eth004

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: !secret use_address_wifi004
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "TTGO-Poe-001 Fallback Hotspot"
    password: !secret fallbackhotspot004

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key004

ota:
  password: !secret ota_pass004

captive_portal:

# Define the port expander hub, here we define one with id 'pcf8574_hub',
# but you can define many

# Example configuration entry
pcf8574:
  - id: 'pcf8574_hub'
    address: 0x20
    pcf8575: false

switch:
  - platform: restart
    name: "T-PoE Restart"
  - platform: gpio
    name: "PCF8574 Pin #0"
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 0
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "PCF8574 Pin #1"
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 1
      number: 1
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: false

# Define binary sensors, use the Arduino PIN number for digital pins and
# for analog use 14 for A0, 15 for A1 and so on...
binary_sensor:
  - platform: gpio
    name: "Input_2"
    pin:
      pcf8574: pcf8574_hub
      number: 2
      mode: INPUT
      inverted: False

web_server:
```

**Comment by RobTillaart** [comment]
@NonaSuomy 
I assume I have to do this on a linux machine - would a RPI work?

**Comment by NonaSuomy** [comment]
Yes the suite of tools is actually streamlined for RPi but you can also install docker for Windows or Mac if you have those. With the RPi build you can just use addons to add esphome. 

https://www.home-assistant.io/installation/raspberrypi/

Once that is up and running follow this to add the esphome add-on https://esphome.io/guides/getting_started_hassio.html

There’s a visual studio add on to home assistant as well if that makes things more streamlined for fun.

https://community.home-assistant.io/t/home-assistant-community-add-on-visual-studio-code/107863

I think they were also including the  RPi pico/W to work with esphome recently not sure its stage of dev.

**Comment by NonaSuomy** [comment]
https://github.com/esphome/esphome/tree/dev/esphome/components/pcf8574

https://github.com/esphome/esphome/tree/dev/esphome/components/rotary_encoder

![image](https://user-images.githubusercontent.com/1906575/204089744-affff555-2b72-493e-af01-63a40e2b3af2.png)

**Comment by NonaSuomy** [comment]
I was speaking to the ESPHome people and they said it's better to just modify the library to work with ESPHome than use it directly.

- they take over gpio pins
- they also take over i2c configuration
- they are not make to be loop friendly and generally have long delay in places which cause issues with esphomes main loop and cause wifi/networking issues

Said to make a folder under your esphome config directory called custom_components

Mine looks like this:
I dumped your files in there and renamed them to expander_rotary_encoder_button.h/cpp to not get confused with the non i2c library one.

```
/esphome/config/custom_components/expander_rotary_encoder/expander_rotary_encoder_button.h/.cpp
```

The folder requires a few more python files to go with it __init__.py and sensor.py for the encoder reporting maybe binary_sensor.py for the button as well.

You can see here:

https://github.com/esphome/esphome/blob/dev/esphome/components/pcf8574/__init__.py

https://github.com/esphome/esphome/blob/dev/esphome/components/rotary_encoder/__init__.py
https://github.com/esphome/esphome/blob/dev/esphome/components/rotary_encoder/sensor.py

The init for the rotary_encoder is blank as it's broken out into sensor.py where as pcf8574 init is just used as general gpio.

The yaml for the esp would look something like this:
```yaml
i2c:
  id: i2c_component
  sda: 14
  scl: 16
  scan: true

# PCF8574 with Rotary Encoder
pcf8574:
  - id: 'pcf8574_hub'
    address: 0x21
    pcf8575: false

# Rotary Encoder A/B Pins
sensor:
  - platform: expander_rotary_encoder_button
    name: "PCF8574 Rotary Encoder (A/B)"
    pin_a: 0
    pin_b: 1
    pcf8574_id: pcf8574_hub
binary_sensor:
  - platform: gpio
    name: "PCF8574 Rotary Encoder Button Pin #2"
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 2
      number: 2
      # One of INPUT or OUTPUT
      mode: INPUT
      inverted: false
```
